apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-deploy-init-bundle-on-all
  namespace: openshift-gitops
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name:  policy-deploy-init-bundle-on-all
        spec:
          remediationAction: inform
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: stackrox
            - complianceType: musthave
              objectDefinition: 
{{ .Files.Get "files/xx00" | indent 16 }}
            - complianceType: musthave
              objectDefinition: 
{{ .Files.Get "files/xx01" | indent 16 }}
            - complianceType: musthave
              objectDefinition: 
{{ .Files.Get "files/xx02" | indent 16 }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-deploy-init-bundle-on-all
  namespace: openshift-gitops
placementRef:
  name: global
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-deploy-init-bundle-on-all
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: global
  namespace: openshift-gitops
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}