# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "init_bundle"
#   createdAt: 2023-04-19T18:56:38.487595468Z
#   expiresAt: 2024-04-18T18:57:00Z
#   id:        bc72768d-16d2-4092-996a-86e9d3ce50b8
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-04-19T18:56:38.487595468Z"
    init-bundle.stackrox.io/expires-at: "2024-04-18T18:57:00Z"
    init-bundle.stackrox.io/id: bc72768d-16d2-4092-996a-86e9d3ce50b8
    init-bundle.stackrox.io/name: init_bundle
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUTHLE9Q3uBeDxT3Ne3BYS/J/NZ7MwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM1NjcwNzA5NTM2MDUwMDE0OTQ1MB4XDTIzMDQxOTE4MTAwMFoXDTI4MDQx
    NzE4MTAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM1NjcwNzA5NTM2MDUwMDE0OTQ1MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE/N+6ekC9paGHX7dYK5+R1XjJNP91C24B5NBf7zs3gkJRnh8S
    lUJOESw7w50Y5d6gFhklSeku0D67pkSW0PYcy6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLD6FFaudgZ7IhOLiCAMFdQB9vqY
    MAoGCCqGSM49BAMCA0kAMEYCIQDW3KGUkMKug6z6/Sz7HK/cMFIhAWCRlkdSDdUX
    VBJnigIhAPbXdTucNkT+1E2vcJb4dPbAUQ6dbhl5lotUZxjrQQSQ
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICtTCCAlqgAwIBAgIJAP75TuBZv/0gMAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTNTY3MDcw
    OTUzNjA1MDAxNDk0NTAeFw0yMzA0MTkxNzU3MDBaFw0yNDA0MTgxODU3MDBaMIGm
    MS0wKwYDVQQKEyRiYzcyNzY4ZC0xNmQyLTQwOTItOTk2YS04NmU5ZDNjZTUwYjgx
    FzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0wOwYDVQQDDDRTRU5TT1JfU0VSVklD
    RTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMR0wGwYDVQQF
    ExQxODM3MjgwMjg4MDMyMDA0NDMyMDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
    BIH94WhvzdgTogfF4iBoATQYjWHl2xKC60kVXwnKrIHuxwSopf3z3FOV3AHNFDf6
    xu8mEuv0neKwD8Tfc5dEnXOjgc4wgcswDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
    MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQg
    SEV/KhXfSSKE+VArxImvm6o8gzAfBgNVHSMEGDAWgBSw+hRWrnYGeyITi4ggDBXU
    Afb6mDBMBgNVHREERTBDgg9zZW5zb3Iuc3RhY2tyb3iCE3NlbnNvci5zdGFja3Jv
    eC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNrcm94LnN2YzAKBggqhkjOPQQDAgNJ
    ADBGAiEA6YNHE36JQ4s0bSj0P1z+xS8g/wBmJ9OscKir4sIaFZACIQCruibMDq3R
    mJHATcrBdLA5G+GdCXnD1garcOWUZQGZ4g==
    -----END CERTIFICATE-----
  acs-host: central-stackrox.apps.cluster-6qjgm.6qjgm.sandbox1439.opentlc.com:443
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIImiEr3MdBzfe79Wou/77MK3+xnsKWvdxv3unoJd4+kzoAoGCCqGSM49
    AwEHoUQDQgAEgf3haG/N2BOiB8XiIGgBNBiNYeXbEoLrSRVfCcqsge7HBKil/fPc
    U5XcAc0UN/rG7yYS6/Sd4rAPxN9zl0Sdcw==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-04-19T18:56:38.487595468Z"
    init-bundle.stackrox.io/expires-at: "2024-04-18T18:57:00Z"
    init-bundle.stackrox.io/id: bc72768d-16d2-4092-996a-86e9d3ce50b8
    init-bundle.stackrox.io/name: init_bundle
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICwjCCAmegAwIBAgIIVBRdQxcbkaYwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExM1NjcwNzA5
    NTM2MDUwMDE0OTQ1MB4XDTIzMDQxOTE3NTcwMFoXDTI0MDQxODE4NTcwMFowgbsx
    LTArBgNVBAoTJGJjNzI3NjhkLTE2ZDItNDA5Mi05OTZhLTg2ZTlkM2NlNTBiODEi
    MCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTFIMEYGA1UEAww/QURN
    SVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
    MDAwMDAwMDAwMDAwMRwwGgYDVQQFExM2MDU4NTY5OTQxNDUyMDM0NDcwMFkwEwYH
    KoZIzj0CAQYIKoZIzj0DAQcDQgAEUEpYKFoOXP+S7W4B5unOVEL9ooWuZ8ioPyQv
    Z0Agy/g/EVFHrVCQ4I5b4XPLu6/EUWmN6xXZXAN4jszpbLTwxKOBxzCBxDAOBgNV
    HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1Ud
    EwEB/wQCMAAwHQYDVR0OBBYEFLa2j/Epj9++NCLDndOdcFyfe8OJMB8GA1UdIwQY
    MBaAFLD6FFaudgZ7IhOLiCAMFdQB9vqYMEUGA1UdEQQ+MDyCGmFkbWlzc2lvbi1j
    b250cm9sLnN0YWNrcm94gh5hZG1pc3Npb24tY29udHJvbC5zdGFja3JveC5zdmMw
    CgYIKoZIzj0EAwIDSQAwRgIhAOqJHKOGjWUHfIHOEiG0r0oV4ODUjFhQNxUFJMN3
    A3tcAiEAoyQ5rctHBXa0VMtPJw8IjTkhdLaDzvJU6/VsHpUwxIY=
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIKS9gO+QPmq3osd7QXVHr1HZa3pZfavIuyjsSf87WD0WoAoGCCqGSM49
    AwEHoUQDQgAEUEpYKFoOXP+S7W4B5unOVEL9ooWuZ8ioPyQvZ0Agy/g/EVFHrVCQ
    4I5b4XPLu6/EUWmN6xXZXAN4jszpbLTwxA==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUTHLE9Q3uBeDxT3Ne3BYS/J/NZ7MwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM1NjcwNzA5NTM2MDUwMDE0OTQ1MB4XDTIzMDQxOTE4MTAwMFoXDTI4MDQx
    NzE4MTAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM1NjcwNzA5NTM2MDUwMDE0OTQ1MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE/N+6ekC9paGHX7dYK5+R1XjJNP91C24B5NBf7zs3gkJRnh8S
    lUJOESw7w50Y5d6gFhklSeku0D67pkSW0PYcy6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLD6FFaudgZ7IhOLiCAMFdQB9vqY
    MAoGCCqGSM49BAMCA0kAMEYCIQDW3KGUkMKug6z6/Sz7HK/cMFIhAWCRlkdSDdUX
    VBJnigIhAPbXdTucNkT+1E2vcJb4dPbAUQ6dbhl5lotUZxjrQQSQ
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-04-19T18:56:38.487595468Z"
    init-bundle.stackrox.io/expires-at: "2024-04-18T18:57:00Z"
    init-bundle.stackrox.io/id: bc72768d-16d2-4092-996a-86e9d3ce50b8
    init-bundle.stackrox.io/name: init_bundle
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUTHLE9Q3uBeDxT3Ne3BYS/J/NZ7MwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM1NjcwNzA5NTM2MDUwMDE0OTQ1MB4XDTIzMDQxOTE4MTAwMFoXDTI4MDQx
    NzE4MTAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM1NjcwNzA5NTM2MDUwMDE0OTQ1MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE/N+6ekC9paGHX7dYK5+R1XjJNP91C24B5NBf7zs3gkJRnh8S
    lUJOESw7w50Y5d6gFhklSeku0D67pkSW0PYcy6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLD6FFaudgZ7IhOLiCAMFdQB9vqY
    MAoGCCqGSM49BAMCA0kAMEYCIQDW3KGUkMKug6z6/Sz7HK/cMFIhAWCRlkdSDdUX
    VBJnigIhAPbXdTucNkT+1E2vcJb4dPbAUQ6dbhl5lotUZxjrQQSQ
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICozCCAkmgAwIBAgIJAKWTMQqDEBDRMAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTNTY3MDcw
    OTUzNjA1MDAxNDk0NTAeFw0yMzA0MTkxNzU3MDBaFw0yNDA0MTgxODU3MDBaMIGs
    MS0wKwYDVQQKEyRiYzcyNzY4ZC0xNmQyLTQwOTItOTk2YS04NmU5ZDNjZTUwYjgx
    GjAYBgNVBAsMEUNPTExFQ1RPUl9TRVJWSUNFMUAwPgYDVQQDDDdDT0xMRUNUT1Jf
    U0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMR0w
    GwYDVQQFExQxMTkzMDkzMzc1OTA1Mjg3ODAzMzBZMBMGByqGSM49AgEGCCqGSM49
    AwEHA0IABOqkvNXJl55/Vcr0WVsl9mB7VqCyoTiK1uBv5FT8LDlU9gLSNR5Pdhxu
    ywMA9fN9FevQQss/RIJUcnnKspRfGrmjgbcwgbQwDgYDVR0PAQH/BAQDAgWgMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1Ud
    DgQWBBRnQY8R+KcAlsd4604h/zYynOZU1TAfBgNVHSMEGDAWgBSw+hRWrnYGeyIT
    i4ggDBXUAfb6mDA1BgNVHREELjAsghJjb2xsZWN0b3Iuc3RhY2tyb3iCFmNvbGxl
    Y3Rvci5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDSAAwRQIhAOOKVWSncsxUsvv/
    kYqikmU5Cdykyz6Wc5VkyGbvnxc2AiAt6dltKs7Ian/Os44UngFDht9SCjslGY4Z
    bZqv6zXQ0Q==
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIJfyGvtHNrS05wslC+dipsJtv3ul1Iq554FFTOaHMyJRoAoGCCqGSM49
    AwEHoUQDQgAE6qS81cmXnn9VyvRZWyX2YHtWoLKhOIrW4G/kVPwsOVT2AtI1Hk92
    HG7LAwD1830V69BCyz9EglRyecqylF8auQ==
    -----END EC PRIVATE KEY-----
