# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "init_bundle"
#   createdAt: 2023-04-19T12:29:09.793895552Z
#   expiresAt: 2024-04-18T12:29:00Z
#   id:        c14e0d1d-ca16-44cf-8b57-e5e5362d7996
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIICvzCCAmWgAwIBAgIIASxx4Z7CETEwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
            U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExMxMjgwMDAx
            MzEyNTc5MDEwODExMB4XDTIzMDQxOTExMjkwMFoXDTI0MDQxODEyMjkwMFowgbkx
            LTArBgNVBAoTJGMxNGUwZDFkLWNhMTYtNDRjZi04YjU3LWU1ZTUzNjJkNzk5NjEi
            MCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTFIMEYGA1UEAww/QURN
            SVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMRowGAYDVQQFExE4NDU2NzcwNjg1ODI5NTYwMTBZMBMGByqG
            SM49AgEGCCqGSM49AwEHA0IABIJSLgtuAXW7S5hdnYSnojkQYqRRE3MBLGsIV+1O
            Y3gaD57w+O7ilQqgLjGZJ8+j2Rl0t2uJnqgloMLp6yjB5QOjgccwgcQwDgYDVR0P
            AQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMB
            Af8EAjAAMB0GA1UdDgQWBBRXstUvbc57MCO7wk/wzrknL3ondTAfBgNVHSMEGDAW
            gBRpvb8HZEp7p/C54Xb0m6iUt1MFEDBFBgNVHREEPjA8ghphZG1pc3Npb24tY29u
            dHJvbC5zdGFja3JveIIeYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3guc3ZjMAoG
            CCqGSM49BAMCA0gAMEUCIQCcV0QsUrLcj2u0pinAp79/ymqr9j5o1BZrevMQ0MpW
            UQIgEl6avdpj+kYzxfT5STemEFj0jtkYjdYAXr7M3cxE/s4=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIEWjqLFVQR34HPV2u5WRZbYe5SLXPcVTCtwedJd0mPaAoAoGCCqGSM49
            AwEHoUQDQgAEglIuC24BdbtLmF2dhKeiORBipFETcwEsawhX7U5jeBoPnvD47uKV
            CqAuMZknz6PZGXS3a4meqCWgwunrKMHlAw==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIB0zCCAXigAwIBAgIUE4ItUa1Is917ErJkCN67aKGLWf0wCgYIKoZIzj0EAwIw
        RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
        VQQFExMxMjgwMDAxMzEyNTc5MDEwODExMB4XDTIzMDQxOTExMzAwMFoXDTI4MDQx
        NzExMzAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
        aXR5MRwwGgYDVQQFExMxMjgwMDAxMzEyNTc5MDEwODExMFkwEwYHKoZIzj0CAQYI
        KoZIzj0DAQcDQgAE+HOkh+xdh2r2vSwzagRii2gnY37TW+gzwiC2QUfcJX2usBNT
        tMNxKrsKeS+wOE4j3THowpuZDAmlsvyKvS3cOKNCMEAwDgYDVR0PAQH/BAQDAgEG
        MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGm9vwdkSnun8LnhdvSbqJS3UwUQ
        MAoGCCqGSM49BAMCA0kAMEYCIQDKVlsZQH+IgnYc1bpI6sSix+J2GtS6fhcUgG8p
        izIVvwIhAOTvAeyhh34I7ukXZcNzkptYICoc6xcPDUfxNGR5prTr
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIICojCCAkegAwIBAgIIauVS9ANa7FMwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
            U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExMxMjgwMDAx
            MzEyNTc5MDEwODExMB4XDTIzMDQxOTExMjkwMFoXDTI0MDQxODEyMjkwMFowgasx
            LTArBgNVBAoTJGMxNGUwZDFkLWNhMTYtNDRjZi04YjU3LWU1ZTUzNjJkNzk5NjEa
            MBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0UxQDA+BgNVBAMMN0NPTExFQ1RPUl9T
            RVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAa
            BgNVBAUTEzc3MDI2NTM5NDU2Njg4ODk2ODMwWTATBgcqhkjOPQIBBggqhkjOPQMB
            BwNCAAT43lF61b6skSgMxEZ9gzQQihHJsVVKLhxZKeh3FacHMdVVuY72o7ZDBdE2
            8FoctEDtMmlQyLPo6k1nvTdLGLVKo4G3MIG0MA4GA1UdDwEB/wQEAwIFoDAdBgNV
            HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
            FgQUB6W5vsOeKUcmUUxp/8ggv8DZBQgwHwYDVR0jBBgwFoAUab2/B2RKe6fwueF2
            9JuolLdTBRAwNQYDVR0RBC4wLIISY29sbGVjdG9yLnN0YWNrcm94ghZjb2xsZWN0
            b3Iuc3RhY2tyb3guc3ZjMAoGCCqGSM49BAMCA0kAMEYCIQC/CwfR9r9RaZdYwA3d
            tziMPYvlo5emnu4xw5AKahbnoQIhANyZJTVmXY764ll3m8ihRMMTAybhEobCzQ4z
            suMUSOJl
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIG3/wDysESNkWEY3CXqhzXiZ8SsEplobZRnfqkGbpeNxoAoGCCqGSM49
            AwEHoUQDQgAE+N5RetW+rJEoDMRGfYM0EIoRybFVSi4cWSnodxWnBzHVVbmO9qO2
            QwXRNvBaHLRA7TJpUMiz6OpNZ703Sxi1Sg==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIICszCCAligAwIBAgIITKb2xHeSvdcwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
            U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExMxMjgwMDAx
            MzEyNTc5MDEwODExMB4XDTIzMDQxOTExMjkwMFoXDTI0MDQxODEyMjkwMFowgaUx
            LTArBgNVBAoTJGMxNGUwZDFkLWNhMTYtNDRjZi04YjU3LWU1ZTUzNjJkNzk5NjEX
            MBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7BgNVBAMMNFNFTlNPUl9TRVJWSUNF
            OiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUT
            EzU1MjMzNzMzMTY2OTY2MjA1MDMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASs
            RU3Zocz7pdcDB6gUS1mGvyvWGaHgzFLOIt2/2XeJdfLMVsFoObbYe/eV9goeP+ZC
            Sn7xX3BK+ZWi2F37gkwWo4HOMIHLMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAU
            BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUXfKz
            Pp88JLOnkM5GaNIeclTD15UwHwYDVR0jBBgwFoAUab2/B2RKe6fwueF29JuolLdT
            BRAwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNrcm94ghNzZW5zb3Iuc3RhY2tyb3gu
            c3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDSQAw
            RgIhAIm4Bh7qxjbqpZgUatakeWbvwU7hm2HRHtv/E2CiaN44AiEA7MI9WIYqJLjc
            0ShuFwITmtPQPFwaSgj9yNk2Oe9pvi8=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEINj1p947doygUZfV2s+ULv45EEBsNuVfF2OMEt2BvNROoAoGCCqGSM49
            AwEHoUQDQgAErEVN2aHM+6XXAweoFEtZhr8r1hmh4MxSziLdv9l3iXXyzFbBaDm2
            2Hv3lfYKHj/mQkp+8V9wSvmVothd+4JMFg==
            -----END EC PRIVATE KEY-----
