# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "init_bundle"
#   createdAt: 2023-04-19T13:07:52.863323394Z
#   expiresAt: 2024-04-18T13:08:00Z
#   id:        db022044-1e27-498c-9d1a-eb3d7384830c
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-04-19T13:07:52.863323394Z"
    init-bundle.stackrox.io/expires-at: "2024-04-18T13:08:00Z"
    init-bundle.stackrox.io/id: db022044-1e27-498c-9d1a-eb3d7384830c
    init-bundle.stackrox.io/name: init_bundle
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUE4ItUa1Is917ErJkCN67aKGLWf0wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExMxMjgwMDAxMzEyNTc5MDEwODExMB4XDTIzMDQxOTExMzAwMFoXDTI4MDQx
    NzExMzAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExMxMjgwMDAxMzEyNTc5MDEwODExMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE+HOkh+xdh2r2vSwzagRii2gnY37TW+gzwiC2QUfcJX2usBNT
    tMNxKrsKeS+wOE4j3THowpuZDAmlsvyKvS3cOKNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGm9vwdkSnun8LnhdvSbqJS3UwUQ
    MAoGCCqGSM49BAMCA0kAMEYCIQDKVlsZQH+IgnYc1bpI6sSix+J2GtS6fhcUgG8p
    izIVvwIhAOTvAeyhh34I7ukXZcNzkptYICoc6xcPDUfxNGR5prTr
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICoDCCAkegAwIBAgIIc+Tf7Anndo8wCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExMxMjgwMDAx
    MzEyNTc5MDEwODExMB4XDTIzMDQxOTEyMDgwMFoXDTI0MDQxODEzMDgwMFowgasx
    LTArBgNVBAoTJGRiMDIyMDQ0LTFlMjctNDk4Yy05ZDFhLWViM2Q3Mzg0ODMwYzEa
    MBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0UxQDA+BgNVBAMMN0NPTExFQ1RPUl9T
    RVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAa
    BgNVBAUTEzgzNTEwNDU4MTM5MjMxODIyMjMwWTATBgcqhkjOPQIBBggqhkjOPQMB
    BwNCAATKVUh5k84lnVNUOrpEkzn0w/njHcCl8VNYs7BoLAvShtB53mSYztNMPZ/F
    Baw7GhK9TPzsP5a/aG3U4TCzS+Y+o4G3MIG0MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUYKvf5EthciE5uoSowx2warnp7zEwHwYDVR0jBBgwFoAUab2/B2RKe6fwueF2
    9JuolLdTBRAwNQYDVR0RBC4wLIISY29sbGVjdG9yLnN0YWNrcm94ghZjb2xsZWN0
    b3Iuc3RhY2tyb3guc3ZjMAoGCCqGSM49BAMCA0cAMEQCIF7jmVSTR2c2qLYgzfZg
    OiJ3Er+3a2eUtq0T6vtQBcO9AiAFRu1Ek/68KmSwy0EZy1+NPZg2V6QR2Jyb0exQ
    27s1Eg==
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEINA140yyfpcvx0wISQYF/P66LzesXx2KQTu79frFErN1oAoGCCqGSM49
    AwEHoUQDQgAEylVIeZPOJZ1TVDq6RJM59MP54x3ApfFTWLOwaCwL0obQed5kmM7T
    TD2fxQWsOxoSvUz87D+Wv2ht1OEws0vmPg==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-04-19T13:07:52.863323394Z"
    init-bundle.stackrox.io/expires-at: "2024-04-18T13:08:00Z"
    init-bundle.stackrox.io/id: db022044-1e27-498c-9d1a-eb3d7384830c
    init-bundle.stackrox.io/name: init_bundle
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUE4ItUa1Is917ErJkCN67aKGLWf0wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExMxMjgwMDAxMzEyNTc5MDEwODExMB4XDTIzMDQxOTExMzAwMFoXDTI4MDQx
    NzExMzAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExMxMjgwMDAxMzEyNTc5MDEwODExMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE+HOkh+xdh2r2vSwzagRii2gnY37TW+gzwiC2QUfcJX2usBNT
    tMNxKrsKeS+wOE4j3THowpuZDAmlsvyKvS3cOKNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGm9vwdkSnun8LnhdvSbqJS3UwUQ
    MAoGCCqGSM49BAMCA0kAMEYCIQDKVlsZQH+IgnYc1bpI6sSix+J2GtS6fhcUgG8p
    izIVvwIhAOTvAeyhh34I7ukXZcNzkptYICoc6xcPDUfxNGR5prTr
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICszCCAlmgAwIBAgIJAIjbAjqkNeQ4MAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTMTI4MDAw
    MTMxMjU3OTAxMDgxMTAeFw0yMzA0MTkxMjA4MDBaFw0yNDA0MTgxMzA4MDBaMIGl
    MS0wKwYDVQQKEyRkYjAyMjA0NC0xZTI3LTQ5OGMtOWQxYS1lYjNkNzM4NDgzMGMx
    FzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0wOwYDVQQDDDRTRU5TT1JfU0VSVklD
    RTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMRwwGgYDVQQF
    ExM5ODYxNDc4MjU5OTQ0MTg2OTM2MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
    jP8zQvGIOQYjU79ACieimUKUuSjrgHbTGzqEKTxpRWY6w2XcqhgOP1tPpfA04SN8
    49Fi9TCntvAUThEpJ+JB0KOBzjCByzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
    FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFPTP
    e6PjqA2e5fQLG+6Q9X20zF/qMB8GA1UdIwQYMBaAFGm9vwdkSnun8LnhdvSbqJS3
    UwUQMEwGA1UdEQRFMEOCD3NlbnNvci5zdGFja3JveIITc2Vuc29yLnN0YWNrcm94
    LnN2Y4Ibc2Vuc29yLXdlYmhvb2suc3RhY2tyb3guc3ZjMAoGCCqGSM49BAMCA0gA
    MEUCIQDvqb3nuTcFeGpw/ZbQ8NAJ+hKMkxzIs83QE+aOCEGKOwIgaFXfQxX3ME1m
    orRi5vDiQfEeeQnSA6sHw1JMRiqDjsA=
    -----END CERTIFICATE-----
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIMgczBWW5lnBPJsGupJT1JHCcLFLe70jH4/pyITjnEy6oAoGCCqGSM49
    AwEHoUQDQgAEjP8zQvGIOQYjU79ACieimUKUuSjrgHbTGzqEKTxpRWY6w2XcqhgO
    P1tPpfA04SN849Fi9TCntvAUThEpJ+JB0A==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-04-19T13:07:52.863323394Z"
    init-bundle.stackrox.io/expires-at: "2024-04-18T13:08:00Z"
    init-bundle.stackrox.io/id: db022044-1e27-498c-9d1a-eb3d7384830c
    init-bundle.stackrox.io/name: init_bundle
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICwjCCAmmgAwIBAgIJAPBz5ZqyL/jcMAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTMTI4MDAw
    MTMxMjU3OTAxMDgxMTAeFw0yMzA0MTkxMjA4MDBaFw0yNDA0MTgxMzA4MDBaMIG8
    MS0wKwYDVQQKEyRkYjAyMjA0NC0xZTI3LTQ5OGMtOWQxYS1lYjNkNzM4NDgzMGMx
    IjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0UxSDBGBgNVBAMMP0FE
    TUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAw
    LTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTczMjY0NDQ2NDQwMDE2NDI3MTYwWTAT
    BgcqhkjOPQIBBggqhkjOPQMBBwNCAATSL+MYNwdcB852Ic2wPppeq4tOhiQv8UwP
    n+gEhK76YHsXFKu3hOkuNbh1ZJ5xhO4a9Er2TvDk3jQNa2Gtqt2jo4HHMIHEMA4G
    A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYD
    VR0TAQH/BAIwADAdBgNVHQ4EFgQU/MBvoaAJXT1Lupk3wbRkaT5Os8AwHwYDVR0j
    BBgwFoAUab2/B2RKe6fwueF29JuolLdTBRAwRQYDVR0RBD4wPIIaYWRtaXNzaW9u
    LWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94LnN2
    YzAKBggqhkjOPQQDAgNHADBEAiAIRRNrJLfrA7EKyDV8i8tdLyCqpQGINos8eu8T
    YoGjNgIgWnf1lDHOZpJvgsMqMCaW4gb+jLjq2jnmz1qNfo7k3Lc=
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIEp3O7n2Uzwf3mUA/fpbYHS/HZbyGWOGE6pLv8gctBSyoAoGCCqGSM49
    AwEHoUQDQgAE0i/jGDcHXAfOdiHNsD6aXquLToYkL/FMD5/oBISu+mB7FxSrt4Tp
    LjW4dWSecYTuGvRK9k7w5N40DWthrardow==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUE4ItUa1Is917ErJkCN67aKGLWf0wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExMxMjgwMDAxMzEyNTc5MDEwODExMB4XDTIzMDQxOTExMzAwMFoXDTI4MDQx
    NzExMzAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExMxMjgwMDAxMzEyNTc5MDEwODExMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE+HOkh+xdh2r2vSwzagRii2gnY37TW+gzwiC2QUfcJX2usBNT
    tMNxKrsKeS+wOE4j3THowpuZDAmlsvyKvS3cOKNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGm9vwdkSnun8LnhdvSbqJS3UwUQ
    MAoGCCqGSM49BAMCA0kAMEYCIQDKVlsZQH+IgnYc1bpI6sSix+J2GtS6fhcUgG8p
    izIVvwIhAOTvAeyhh34I7ukXZcNzkptYICoc6xcPDUfxNGR5prTr
    -----END CERTIFICATE-----
