---
# Based on : https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
# Based on : https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html#ansible-collections-kubernetes-core-k8s-info-module
- name: "RH Summit Demo - Part 0 - Ansible install GitOps Operator"
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    git_repo: "https://github.com/tommeramber/Compliance-As-Code.git"
  collections:
    - lvrfrc87.git_acp
  tasks:
  
          #    - include_role:
          #        name: install-and-configure-openshift-gitops-operator 
          #
          #    - include_role:
          #        name: acm-openshift-gitops-integration
          #
          #    - include_role:
          #        name: deploy-app-of-apps
          #
#    - include_role:
#       name: git-add-commit-and-push
#---
    - name: "SSH Push all updated YAMLs to Git for ArgoCD"
      git_acp:
        path: .
        branch: main
        comment: Add all.
        add: [ "." ]
        url: "{{ git_repo }}"
