---
# Based on : https://docs.ansible.com/ansible/latommeramber/collections/kubernetes/core/k8s_module.html
# Based on : https://docs.ansible.com/ansible/latommeramber/collections/kubernetes/core/k8s_info_module.html#ansible-collections-kubernetes-core-k8s-info-module
- name: "RH Summit Demo - Part 0 - Ansible install GitOps Operator"
  hosts: localhost
  gather_facts: false
  connection: local
  
  vars:
    git_repo: "git@github.com:tommeramber/Compliance-As-Code.git"

  tasks:
          #    - include_role:
          #        name: install-and-configure-openshift-gitops-operator 
          #    
          #    - include_role:
          #        name: acm-openshift-gitops-integration
          #    
          #    - include_role:
          #        name: deploy-app-of-apps
          #    
          #    - name: "SSH Push all updated YAMLs to Git for ArgoCD"
          #      shell: "git add --all :/ ; git commit -m initial-ansible-playbook ; git push"

    - include_role:
        name: create-acs-init-bundle
    
    - name: "SSH Push all updated YAMLs to Git for ArgoCD"
      shell: "git add --all :/ ; git commit -m Import-managed-clusters-to-ACS ; git push"
