---
# Based on : https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
# Based on : https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html#ansible-collections-kubernetes-core-k8s-info-module
- name: "RH Summit Demo - Part 0 - Ansible install GitOps Operator"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - include_role:
        name: install-and-configure-openshift-gitops-operator 
      # Pause betweeen roles so the Openshift-GitOps operator will finish creating the relevant Namespace and CRDs
    - pause:
        seconds: 120
    - include_role:
        name: acm-openshift-gitops-integration
