apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policies
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/tommeramber/Compliance-As-Code.git
      revision: HEAD
      directories:
      - path: ../Part2-Compliance-as-GitOps/policies/*
      - path: ../Part2-Compliance-as-GitOps/policies
        exclude: true
  template:
    metadata:
      name: {{`'{{path.basename}}'`}}
    spec:
      project: default 
      source:
        repoURL: https://github.com/tommeramber/Compliance-As-Code.git
        targetRevision: HEAD
        path: {{`'{{path}}'`}}
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
      syncPolicy: 
        automated: {}
